[project]
# The name of your game's executable. This should only contain a-z, A-Z, 0-9, _ or -.
name = "particle"
# The game's title. This will show up in the tile bar of your executable.
title = "particle"
version = "0.1.0"
authors = ["levi"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "4.0"
edition = "pro"

[dependencies]
# none~
